### ISSUE TITLE
in conjunction with courseplay i get an error on courseplay wich i dont get without the dynamicfieldprices.  (hriel@live.nl)

### ISSUE THREAD

**Issue by Hilbert1982** [BigFood2307/FS22_DynamicFieldPrices#2]
[log.txt](https://github.com/BigFood2307/FS22_DynamicFieldPrices/files/8111865/log.txt)

**Comment by BigFood2307** [comment]
Hey,
thanks for reporting this.
Unfortunately I can not replicate the error. Loading up CP + DFP works just fine for me.
Could you give some context òn what you were doing when it crashes? Is it during loading, just as you hit enter, or were you able to actually do something ingame before it crashed?
Since you have a lot of mods: Could you test loading up a new save with only those two mods?
From a first look, there is no reason my mod should influence that error you get in the end. Obviously there can always be weird side effects, but without more info, I dont think I can fix this. Sorry

**Comment by Hilbert1982** [comment]
so i tried to recreate the problem and make a video of it and there is no problem any more. so i did this 3 times and every time there was no problem and the game just loaded fin
![fsScreen_2022_02_23_21_26_23](https://user-images.githubusercontent.com/97124680/155402525-0a17dba1-25ed-404e-bef5-85b3cf54fec3.png)
e
