### ISSUE TITLE
Overlapping Text/Percentage

### ISSUE THREAD

**Issue by matze0301** [BigFood2307/FS22_DynamicFieldPrices#3]
![fsScreen_2022_03_18_19_36_14](https://user-images.githubusercontent.com/63884367/159064041-90a7349e-6883-404d-9b48-e591e956916d.png)

The percentage overlaps with the text and is sometimes hard to read, mostly on positive values.
Is there a chance for a fix?

And thank you for this gread mod :-)

**Comment by BigFood2307** [comment]
Hey, thanks for the report!
I use a ultra wide screen monitor (21:9). That may have been the problem there. Did not realize the position is relative...
The newest version now leaves a bit more space.
I tested it with a 16:9 resolution and there should not be any more overlap. You can download it here if you want, since I dont know how long modhub will take for the update.
